# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [21]:
# Find the establishments with a hygiene score of 20
hygiene = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
count = db.establishments.count_documents(hygiene)
pprint(count)
pprint("")
# Display the first document in the results using pprint
h_list = list(establishments.find(hygiene))
pprint(h_list[0])

41
''
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('667cadb9a91032d172927110'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [19]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.json_normalize(h_list)
# Display the number of rows in the DataFrame
print(len(hygiene_df))
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,667cadb9a91032d172927110,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,667cadb9a91032d172927498,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,667cadb9a91032d1729277b4,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,667cadb9a91032d17292798a,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,667cadb9a91032d172927997,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,667cadb9a91032d172928336,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,667cadb9a91032d172928559,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,667cadb9a91032d172929a85,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,667cadb9a91032d172929ec8,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,667cadb9a91032d17292a6d9,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [26]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4. LOCAL AUTHORITY IS NOT LONDON, ITS CITY OF LONDON COPORATION
London = {"AddressLine2": 'London', "RatingValue": {'$gte': 4}}

# Use count_documents to display the number of documents in the result
count = db.establishments.count_documents(London)
pprint(count)
pprint("")
# Display the first document in the results using pprint
lon_list = list(establishments.find(London))
pprint(lon_list[0])

99
''
{'AddressLine1': 'Reeds River Cruises LtdKings ReachRiver ThamesSouthwark',
 'AddressLine2': 'London',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': 'Mv Valulla',
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4640.460834256174,
 'FHRSID': 294900,
 'LocalAuthorityBusinessID': 'PI/000019066',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'RM15 5QY',
 'RatingDate': '2016-08-23T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('667cadbaa91032d17292aeaa'),
 'geocode': {'latitude': 51.504071, 'longitude': 0.287555},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/294900',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

In [27]:
# Convert the result to a Pandas DataFrame
london_df = pd.json_normalize(lon_list)
# Display the number of rows in the DataFrame
print(len(london_df))
# Display the first 10 rows of the DataFrame
london_df.head(10)

99

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,667cadbaa91032d17292aeaa,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,667cadbaa91032d17292c43a,1408389,0,21/00294/CP,Foodyz21,Restaurant/Cafe/Canteen,1,513 Abbey Road,London,,...,0.121862,51.489920,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,667cadbaa91032d17292c44e,1156030,0,PI/000297297,Bona,Restaurant/Cafe/Canteen,1,25 Dartmouth Road,London,,...,0.014344,51.383120,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,667cadbaa91032d17292c458,1438466,0,22/00008/CP,Finest Chicken Peri Peri Grill,Takeaway/sandwich shop,7844,515 Abbey Road,London,,...,0.121542,51.489926,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,667cadbaa91032d17292c4d5,776404,0,15/00376/CP,Toddleswood Pre-School At Willowbank School,Caring Premises,5,Seacourt Road,London,,...,0.125247,51.497376,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,667cadbaa91032d17292c4e2,930899,0,16/00266/CP,The Contract Dining Company At Willow Bank Pri...,School/college/university,7845,Seacourt Road,London,,...,0.125247,51.497376,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,667cadbaa91032d17292c4f1,875250,0,14/00066/CP,The Ness Cafe,Restaurant/Cafe/Canteen,1,Belvedere Road,London,,...,0.133478,51.506094,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,667cadbaa91032d17292c501,1064870,0,18/00191/CP,Turo Turo,Mobile caterer,7846,2 Portmeadow Walk,London,,...,0.125037,51.498425,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,667cadbaa91032d17292c5ab,1223157,0,20/00040/CP,Falconwood Food & Wine,Retailers - other,4613,15 Lingfield Crescent,London,,...,0.081220,51.459120,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,667cadbaa91032d17292c5ad,996676,0,17/00248/CP,Falcon News,Retailers - other,4613,1 Lingfield Crescent,London,,...,0.081220,51.459122,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [35]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.086058
longitude = 1.196408
rating_value = 5

query = {'geocode.latitude': {'$gte': latitude-degree_search, '$lt': latitude+degree_search},
         'geocode.longitude': {'$gte': longitude-degree_search, '$lt': longitude+degree_search},
         'RatingValue': rating_value}
# filter = {'BusinessName': 1}
sort = [('scores.Hygiene', -1)]
limit = 5

# Print the results
lat_list = list(establishments.find(query).sort(sort).limit(limit))
pprint(lat_list)

[{'AddressLine1': 'Little Switzerland Caravan Site',
  'AddressLine2': 'Wear Bay Road',
  'AddressLine3': 'Folkestone',
  'AddressLine4': 'Kent',
  'BusinessName': 'Little Switzerland Cafe',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4591.952041503925,
  'FHRSID': 548374,
  'LocalAuthorityBusinessID': 'PI/000063956',
  'LocalAuthorityCode': '188',
  'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
  'LocalAuthorityName': 'Folkestone and Hythe',
  'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CT19 6PS',
  'RatingDate': '2019-04-24T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('667cadb8a91032d172925610'),
  'geocode': {'latitude': 51.095015, 'longitude': 1.202055},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/548374',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': '23 The Stade',
  'AddressLine2': 'Folkestone',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'The Ship',
  'BusinessType': 'Pub/bar/nightclub',
  'BusinessTypeID': 7843,
  'ChangesByServerID': 0,
  'Distance': 4591.912144538092,
  'FHRSID': 289352,
  'LocalAuthorityBusinessID': 'PI/000002460',
  'LocalAuthorityCode': '188',
  'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
  'LocalAuthorityName': 'Folkestone and Hythe',
  'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CT19 6AB',
  'RatingDate': '2015-08-27T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('667cadb8a91032d1729255e6'),
  'geocode': {'latitude': 51.08084, 'longitude': 1.188537},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/289352',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}},
 {'AddressLine1': 'The Durlocks',
  'AddressLine2': 'Folkestone',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'St Peters Church Of England Primary School',
  'BusinessType': 'School/college/university',
  'BusinessTypeID': 7845,
  'ChangesByServerID': 0,
  'Distance': 4591.999712242712,
  'FHRSID': 289351,
  'LocalAuthorityBusinessID': 'PI/000002381',
  'LocalAuthorityCode': '188',
  'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
  'LocalAuthorityName': 'Folkestone and Hythe',
  'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CT19 6AH',
  'RatingDate': '2019-09-09T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('667cadb8a91032d17292561f'),
  'geocode': {'latitude': 51.081735, 'longitude': 1.187056},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/289351',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 0}},
 {'AddressLine1': '4 Back Street',
  'AddressLine2': 'Folkestone',
  'AddressLine3': 'Kent',
  'AddressLine4': '',
  'BusinessName': 'Sandys',
  'BusinessType': 'Takeaway/sandwich shop',
  'BusinessTypeID': 7844,
  'ChangesByServerID': 0,
  'Distance': 4591.959734543383,
  'FHRSID': 1273628,
  'LocalAuthorityBusinessID': 'PI/000072454',
  'LocalAuthorityCode': '188',
  'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
  'LocalAuthorityName': 'Folkestone and Hythe',
  'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CT19 6NN',
  'RatingDate': '2021-10-10T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('667cadb8a91032d172925612'),
  'geocode': {'latitude': 51.080446, 'longitude': 1.186825},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1273628',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 0, 'Hygiene': 5, 'Structural': 0}},
 {'AddressLine1': 'East Cliff Pavilion',
  'AddressLine2': 'Wear Bay Road',
  'AddressLine3': 'Folkestone',
  'AddressLine4': 'Kent',
  'BusinessName': 'The Pavilion',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4591.765489457773,
  'FHRSID': 1043695,
  'LocalAuthorityBusinessID': 'PI/000073616',
  'LocalAuthorityCode': '188',
  'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
  'LocalAuthorityName': 'Folkestone and Hythe',
  'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CT19 6BL',
  'RatingDate': '2018-04-04T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': 5,
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('667cadb8a91032d1729255dc'),
  'geocode': {'latitude': 51.083812, 'longitude': 1.195625},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1043695',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}]

In [36]:
# Convert result to Pandas DataFrame
lat_df = pd.json_normalize(lat_list)

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [39]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': 0}}

# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': {"LocalAuthorityName": "$LocalAuthorityName"},'count': { '$sum': 1 }}}

# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1 }}

# Print the number of documents in the result
pipeline = [match_query, group_query, sort_values]

# Print the first 10 results
results = list(establishments.aggregate(pipeline))
print("Number of rows in result: ", len(results))

Number of rows in result:  55

In [40]:
# Convert the result to a Pandas DataFrame
results_df = pd.json_normalize(results)
# Display the number of rows in the DataFrame
print(len(results_df))
# Display the first 10 rows of the DataFrame
results_df.head(10)

55

   count _id.LocalAuthorityName
0   1130                 Thanet
1    882              Greenwich
2    713              Maidstone
3    711                 Newham
4    686                  Swale
5    680             Chelmsford
6    672                 Medway
7    607                 Bexley
8    586        Southend-On-Sea
9    542               Tendring